[workspace]
resolver = "2"
members = [
  "crates/protoc-gen-protovalidate-buffa",
  "crates/protovalidate-buffa",
  "crates/protovalidate-buffa-conformance",
  "crates/protovalidate-buffa-macros",
  "crates/protovalidate-buffa-protos",
]

[workspace.package]
authors = ["Mathematic Inc"]
edition = "2024"
rust-version = "1.88"
homepage = "https://github.com/mathematic-inc/protovalidate-buffa"
repository = "https://github.com/mathematic-inc/protovalidate-buffa"
license = "Apache-2.0 OR MIT"
keywords = ["buffa", "codegen", "protobuf", "protovalidate", "validation"]
categories = ["development-tools", "network-programming"]

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
