[package]
name = "protovalidate-buffa-protos"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Compiled Rust types for buf/validate/validate.proto (for buffa), consumed by protoc-gen-protovalidate-buffa."
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
buffa = "0.9.1"
buffa-descriptor = "0.9.1"
buffa-types = "0.9.1"

[build-dependencies]
buffa-build = "0.9.1"

[lints]
workspace = true
