syntax = "proto2";

package acme.v1;

import "buf/validate/validate.proto";

extend buf.validate.StringRules {
  optional bool language_tag = 500001 [(buf.validate.predefined).cel = {
    id: "string.language_tag"
    expression: "!rule || this.matches('^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$')"
  }];
}

message Outer {
  message Inner {
    extend buf.validate.StringRules {
      optional bool language_tag = 500002 [(buf.validate.predefined).cel = {
        id: "string.nested_language_tag"
        expression: "!rule || this.matches('^[a-z]{2}$')"
      }];
    }
  }
}

message RequiredValue {
  required string locale = 1 [
    (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE,
    (buf.validate.field).cel = {
      id: "required.cel"
      expression: "false"
    },
    (buf.validate.field).string.(language_tag) = true
  ];
}
